### ISSUE TITLE
Support stuff without authentication

### ISSUE THREAD

**Issue by GeertvanHorrik** [jonas0007/Jira.SDK#4]
I think that it's not possible to check out public JIRA instances. For example, I use this:

```
jira.Connect("someurl", null, null);
```

Even in that case, you create the auth values:

https://github.com/jonas0007/Jira.SDK/blob/master/Jira.SDK/JiraClient.cs#L74

I think the auth values should only be created when both username / password are provided.

**Comment by jonas0007** [comment]
Added a new commit to master which adds a new method jira.Connect("someurl"). This code path will not add the authentication parameter to the RestSharp instance. I'm currently not able to test this out because I'm not ably to access my Jira instance at the moment but please feel free to test it out yourself. Let me know if this fixes your issue.

**Comment by GeertvanHorrik** [comment]
Did you also release a new nuget package? I use https://catelproject.atlassian.net/secure/Dashboard.jspa for testing.

**Comment by jonas0007** [comment]
I've published a new nuget packag which now supports unauthenticated access to Jira.

**Comment by GeertvanHorrik** [comment]
Thanks!
